### ISSUE TITLE
Update to `elm-explorations/test@2.2.0`

### ISSUE THREAD

**Issue by kutyel** [niho/json-schema-form#8]
I know this feels like a long shot, I might even provide the PR myself, but adding this package made our test suit drop from 2.2 to 1.2.2, which causes all our tests to fail... So I guess the correct thing is to fix this tests 🙏🏻 😉

**Comment by niho** [comment]
Hi Flavio, I looked into it just now to help you out. But unfortunately there is a dependency conflict with the `etaque/elm-form` package, which is dependent on `elm-exploration/test` version 1.0.0 <= v < 2.0.0. Since elm-form is a core dependency of json-schema-form it is not possible to upgrade to 2.2.0.

But you might be able to convince the maintainer of `etaque/elm-form` to upgrade. Then I will in turn be able to upgrade the dependency in this package. You are welcome to reopen the issue if you get it fixed and I will take a look at it again.

**Comment by kutyel** [comment]
Thanks for trying Niklas, opened another issue in that repo https://github.com/etaque/elm-form/issues/121 👀

**Comment by kutyel** [comment]
You can now rely on my package and make yours compatible with the latest version! 🙌🏻 

https://package.elm-lang.org/packages/kutyel/elm-form/1.0.0/
